# Generated by Django 4.1.5 on 2023-02-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_rename_super_types_supers_super_type'),
        ('super_types', '0002_super_types_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Super_types',
            new_name='SuperType',
        ),
    ]
