# Generated by Django 4.1.5 on 2023-03-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0003_rename_super_types_supertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supertype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
