# Generated by Django 4.1.5 on 2023-01-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='super_type',
            new_name='super_types',
        ),
    ]
