# Generated by Django 4.1.5 on 2023-01-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_rename_super_type_supers_super_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='super_types',
            new_name='super_type',
        ),
    ]
