# Generated by Django 4.1.5 on 2023-02-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0003_rename_super_types_supertype'),
        ('supers', '0003_rename_super_types_supers_super_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supers',
            new_name='Super',
        ),
        migrations.RenameField(
            model_name='super',
            old_name='catch_phrase',
            new_name='catchphrase',
        ),
    ]
